version: !!str 3.7

services:
  cxp:
    build: 
      context: ${{CONTEXT}}
      dockerfile: ./Dockerfile
    container_name: container-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      CONTAINER_EXPORTER_PORT: ${CONTAINER_EXPORTER_PORT}
    ports:
      - 8000:8000
    restart: always