---

- name : Checkout the repo
  git:
    repo: "{{repo_addr}}"
    dest: "{{repo_path}}"

- name: create venv
  shell: python3 -m venv venv

- name : build cxp 
  shell : source "{{repo_path}}/venv/bin/activate" && pip install -U pip && pip install -r "{{repo_path}}/requirements.txt"

- name: deploy cxp
  shell: bash {{repo_path}}/start.sh &