name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'extra/**'
      - 'capture/**'
      - 'ansible/**'
      - 'dashboards/**'
      - 'scripts/**'
      - '.gitignore'
      - 'LICENSE'
    branches:
      - master

env:
  ghcr_repo_addr: ghcr.io/shayan-ghani/container-exporter:latest
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: deploy from ghcr
        run: |
          IMAGE=${{env.ghcr_repo_addr}} docker compose -f ./container-exporter.yml up -d