name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'extra/**'
      - 'capture/**'
      - 'ansible/**'
      - 'dashboards/**'
      - 'scripts/**'
      - '.gitignore'
      - 'LICENSE'


env:
  ghcr_repo_addr: ghcr.io/shayan-ghani/container-exporter:pr-${{github.run_id}}
  
jobs:
  
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build and export to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{env.ghcr_repo_addr}}



  healthcheck:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }} 
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: deploy from ghcr
        run: |
          IMAGE=${{env.ghcr_repo_addr}} docker compose -f ./container-exporter.yml up -d
        
      - name: check metrics api and print out metrics
        run: |
          bash ./scripts/healthcheck-ci.sh


  # test:
    
  # ## pytest to be implemented here ...