name: Dependency Security & Compatibility Test

on:
  pull_request:
    paths:
      - 'requirements.txt'
      - '**.py'

jobs:
  test-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pip-audit to report vulnerabilities
        run: |
          pip install pip-audit
          pip-audit || true  

      - name: Deploy cxp
        run: |
          bash ./start.sh &
          sleep 5

      - name: Run Application Health Check
        run: |
          bash ./scripts/healthcheck-ci.sh