name: CI-development

on:
  push:
    branches-ignore:
        - 'main'
        - 'master'
    
    paths-ignore:
      - '**.md'
      - 'extra/**'
      - 'capture/**'
      - 'ansible/**'
      - 'dashboards/**'
      - '.gitignore'
      - 'LICENSE'
      
  pull_request:
    paths-ignore:
      - '**.md'
      - 'extra/**'
      - 'capture/**'
      - 'ansible/**'
      - 'dashboards/**'
      - 'scripts/**'
      - '.gitignore'
      - 'LICENSE'


env:
  ghcr_repo_addr: ghcr.io/shayan-ghani/container-exporter:${{github.action}}-${{github.run_id}}
  
jobs:  
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: build and deploy
        run: |
          docker compose -f ./container-exporter-local.yml up --build -d
        
      - name: check for metrics and overall api health
        run: |
          bash ./scripts/healthcheck-ci.sh
