name: Github Releaase

on:
    push:
      paths-ignore:
        - '**.md'
        - 'extra/**'
        - 'capture/**'
        - 'ansible/**'
        - 'dashboards/**'
        - 'scripts/**'
        - '.gitignore'
        - 'LICENSE'
      branches:
        - master

env:
  ghcr_repo_addr: ghcr.io/shayan-ghani/container-exporter:latest
  
jobs:
  release:
    if: github.event_name != 'pull_request' && github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - 
        name: Bump version and push tag
        id: bump
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
  
  
      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          body: ${{ steps.bump.outputs.changelog }}
          tag_name: ${{ steps.bump.outputs.new_tag }}